### ISSUE TITLE
Please add a screenshot of the theme in use

### ISSUE THREAD

**Issue by unixorn** [ruisaraiva19/saraiva-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by ruisaraiva19** [comment]
@unixorn Just added terminal and visual studio code screenshots!

**Comment by unixorn** [comment]
Cool. Adding to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) as of 4a7e54b.
